package com.example.demo.utils;

public class DataCheck {
    public enum UserDataCheck{
        USERID_NOT_EXISTS, USERID_IS_EMPTY, USERID_IS_TOO_LONG, PASSWORD_IS_EMPTY,
        PASSWORD_TOO_SHORT,PASSWORD_TOO_LONG,USER_ROLE_ERROR,USERNAME_IS_EMPTY,
        PHONE_IS_EMPTY,ILLEGAL_TELEPHONE,USERNO_NOT_EXISTS,ACCOUNT_CAN_USE,PERMISSION_DENIED,
        EMPTY_TITLE, USERID_EXISTS
    }
}
